name: testapp_aoi
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  custom_sliding_segmented_control: ^1.8.1
  flutter:
    sdk: flutter
  flutter_dismissible_tile: ^1.0.2
  flutter_swipe_action_cell: ^3.1.2
  image_picker: ^1.0.4
  pinput: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/


